"""add users table and user_id to farms

Revision ID: 92ed82f92c93
Revises: 774627a55c7d
Create Date: 2026-04-10 17:11:42.003939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ed82f92c93'
down_revision: Union[str, Sequence[str], None] = '774627a55c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('farms', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'farms', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'weather_readings', 'farms', ['farm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather_readings', type_='foreignkey')
    op.drop_constraint(None, 'farms', type_='foreignkey')
    op.drop_column('farms', 'user_id')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
